# -*- coding: utf-8 -*-
"""Copy of Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p0G-5qi4TDA0RkC1oY5AJvMmmpWajkiq
"""

from google.colab import drive
drive.mount('/content/drive',force_remount=True)

"""After mounting your Google Drive, you can list the contents of your Drive to find the file you want to load. For example, to list the contents of your root Google Drive folder, you can run:"""

import pandas as pd
import numpy as np
import os

!ls /content/drive/My\ Drive/

"""Once you have the path to your file, you can load it using the appropriate library (e.g., pandas for CSV files). Please let me know the file type and its path, and I can help you load it.

### 1. Data Pipeline & Feature Engineering

#### A. Data Processing: Loading and Initial Cleaning

Assuming your cryptocurrency data is in CSV format and stored in a Google Drive folder, here's how you can set up a loop to load them. You'll need to specify the path to your folder.
"""

import pandas as pd
import numpy as np
import os

crypto_data_folder = '/content/drive/My Drive/JETs Intrasoc Hackathon/'

all_crypto_data = {}

# List all files in the specified folder
# You might need to filter for .csv files if there are other files in the directory
for filename in os.listdir(crypto_data_folder):
    if filename.endswith('.csv'):
        crypto_name = filename.replace('.csv', '') # Extract crypto name from filename
        filepath = os.path.join(crypto_data_folder, filename)
        print(f"Loading {crypto_name} data from {filepath}...")
        try:
            df = pd.read_csv(filepath)

            # Rename 'Date' to 'date' and 'Close' to 'close' as per user's data
            df = df.rename(columns={'Date': 'date', 'Close': 'close'})

            # Convert 'date' column to datetime objects and ensure 'close' exists
            if 'date' in df.columns and 'close' in df.columns:
                df['date'] = pd.to_datetime(df['date'])
                df = df.sort_values(by='date') # Ensure data is sorted by date
                all_crypto_data[crypto_name] = df
            else:
                print(f"Required columns 'Date' or 'Close' not found (or could not be renamed) in {crypto_name}. Skipping this file.")

        except Exception as e:
            print(f"Error loading {filename}: {e}")

print(f"\nSuccessfully loaded data for {len(all_crypto_data)} cryptocurrencies.")

# Display the first few rows of one of the loaded datasets as an example
if all_crypto_data:
    first_crypto_name = list(all_crypto_data.keys())[0]
    print(f"\nFirst 5 rows of {first_crypto_name} data:")
    display(all_crypto_data[first_crypto_name].head())
else:
    print("No cryptocurrency data loaded. Please check the folder path and file formats.")

"""#### B. Feature Extraction

Now, let's define a function to extract meaningful features like daily returns, moving averages, and volatility. We'll apply this function to each dataset.

For a lightweight classification model predicting 'UP' or 'DOWN' for the *next day's close*, we need to define our target variable. A common approach is to look at the percentage change between today's close and tomorrow's close.
"""



"""#### C. Data Quality Checks and Cleaning

Before we dive deeper into feature engineering, let's perform some essential data quality checks. This involves looking for missing values, understanding data distributions, and identifying potential outliers. We will apply these checks to one of the loaded cryptocurrency datasets as an example.
"""

if all_crypto_data:
    # Pick an example cryptocurrency for detailed data quality check
    example_crypto_name = list(all_crypto_data.keys())[0]
    example_df = all_crypto_data[example_crypto_name]

    print(f"\n--- Data Quality Report for {example_crypto_name} ---")

    # 1. Check for Missing Values
    print("\nMissing values per column:")
    display(example_df.isnull().sum())

    # 2. Display Descriptive Statistics
    print("\nDescriptive Statistics:")
    display(example_df.describe())

    # 3. Check for obvious outliers in 'close' price (e.g., negative prices, extreme values)
    print("\nMin/Max 'close' price:")
    print(f"Min Close: {example_df['close'].min()}")
    print(f"Max Close: {example_df['close'].max()}")

    # You can also visualize distributions for outliers, e.g., using box plots
    import matplotlib.pyplot as plt
    import seaborn as sns

    plt.figure(figsize=(10, 6))
    sns.boxplot(y=example_df['close'])
    plt.title(f'Box Plot of Close Price for {example_crypto_name}')
    plt.ylabel('Close Price')
    plt.show()

    # Further cleaning actions can be added here if issues are identified
    # For instance, removing rows with significant missing data, capping outliers, etc.
    # For now, we'll proceed assuming the `dropna()` in feature engineering is sufficient for initial NaNs.
else:
    print("No cryptocurrency data available for quality checks. Please ensure data is loaded successfully.")

def engineer_features(df):
    # Ensure 'close' column exists; adjust column names if necessary
    if 'close' not in df.columns:
        print("Warning: 'close' column not found. Skipping feature engineering.")
        return df

    # 1. Daily Returns
    df['daily_return'] = df['close'].pct_change() * 100

    # 2. Moving Averages
    df['ma_7'] = df['close'].rolling(window=7).mean()
    df['ma_14'] = df['close'].rolling(window=14).mean()
    df['ma_30'] = df['close'].rolling(window=30).mean()

    # 3. Volatility Indexes (e.g., 7-day rolling standard deviation of daily returns)
    df['volatility_7'] = df['daily_return'].rolling(window=7).std()
    df['volatility_14'] = df['daily_return'].rolling(window=14).std()

    # 4. Target Variable: Next Day's Price Movement (UP/DOWN)
    # Shift the close price to get the next day's close price
    df['next_day_close'] = df['close'].shift(-1)
    # Calculate next day's percentage change
    df['next_day_pct_change'] = ((df['next_day_close'] - df['close']) / df['close']) * 100
    # Define 'UP' (1) if next day's close is higher, 'DOWN' (0) otherwise
    df['target'] = (df['next_day_pct_change'] > 0).astype(int)

    # Drop rows with NaN values that result from feature engineering (e.g., beginning of rolling windows)
    df = df.dropna()

    return df

# Apply feature engineering to all loaded cryptocurrency datasets
processed_crypto_data = {}
for crypto_name, df in all_crypto_data.items():
    print(f"Engineering features for {crypto_name}...")
    processed_df = engineer_features(df.copy()) # Use .copy() to avoid SettingWithCopyWarning
    if not processed_df.empty:
        processed_crypto_data[crypto_name] = processed_df
    else:
        print(f"No data after feature engineering for {crypto_name}. It might be too short.")

print(f"\nSuccessfully engineered features for {len(processed_crypto_data)} cryptocurrencies.")

# Display the features for one example cryptocurrency
if processed_crypto_data:
    example_crypto = list(processed_crypto_data.keys())[0]
    print(f"\nFeatures for {example_crypto} (first 5 rows):")
    display(processed_crypto_data[example_crypto].head())
    print(f"\nLast 5 rows for {example_crypto} (to check target variable):")
    display(processed_crypto_data[example_crypto].tail())
else:
    print("No processed data available after feature engineering.")

"""### 2. Model Training and Evaluation

Now, let's prepare the data for training, select a lightweight classification model, train it, and evaluate its performance.
"""

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report
import pandas as pd # Ensure pandas is imported

trained_models = {}
model_evaluations = {}
feature_names_for_export = None # To store feature names once for export

for crypto_name, df in processed_crypto_data.items():
    print(f"\n--- Training and evaluating model for {crypto_name} ---")

    # Define features (X) and target (y)
    current_X = df[['daily_return', 'ma_7', 'ma_14', 'ma_30', 'volatility_7', 'volatility_14']]
    current_y = df['target']

    # Store feature names from the first crypto's X for export later
    if feature_names_for_export is None:
        feature_names_for_export = current_X.columns.tolist()

    # Handle potential NaN values
    current_X = current_X.dropna()
    current_y = current_y[current_X.index] # Ensure y aligns with cleaned X

    if len(current_X) == 0:
        print(f"Not enough data for {crypto_name} after dropping NaNs. Skipping model training.")
        continue

    print(f"Total samples for {crypto_name}: {len(current_X)}")

    # Split data into training and testing sets
    X_train, X_test, y_train, y_test = train_test_split(current_X, current_y, test_size=0.2, random_state=42, stratify=current_y)

    print(f"Training set size for {crypto_name}: {len(X_train)} samples")
    print(f"Testing set size for {crypto_name}: {len(X_test)} samples")

    # Initialize and train a Logistic Regression model
    current_model = LogisticRegression(random_state=42, solver='liblinear')
    current_model.fit(X_train, y_train)

    print(f"Model training complete for {crypto_name}.")
    trained_models[crypto_name] = current_model

    # Make predictions on the test set
    y_pred = current_model.predict(X_test)

    # Evaluate the model
    accuracy = accuracy_score(y_test, y_pred)
    report = classification_report(y_test, y_pred)

    model_evaluations[crypto_name] = {
        'accuracy': accuracy,
        'report': report
    }

    print(f"\nModel Accuracy for {crypto_name}: {accuracy:.4f}")
    print(f"\nClassification Report for {crypto_name}:\n{report}")

print("\n--- All models trained and evaluated ---")

"""### 3. Model Export for Frontend Inference

To use these models in a JavaScript frontend, we need to export their weights. For scikit-learn models like Logistic Regression, a common approach is to export their parameters (coefficients and intercept) as a JSON object for each model, which can then be loaded and used in a custom JavaScript prediction function. Another more robust option for complex models would be to use `joblib` to save the model and then potentially convert it to TensorFlow.js format if you switch to a Keras/TensorFlow model.

For these lightweight Logistic Regression models, exporting coefficients for each cryptocurrency is straightforward:
"""

import json

all_crypto_model_params = {}

if trained_models and feature_names_for_export:
    for crypto_name, model_obj in trained_models.items():
        # Extract coefficients and intercept
        coefficients = model_obj.coef_.tolist()[0]
        intercept = model_obj.intercept_.tolist()[0]

        # Create a dictionary to hold the model parameters for the current crypto
        model_params = {
            'coefficients': dict(zip(feature_names_for_export, coefficients)),
            'intercept': intercept
        }
        all_crypto_model_params[crypto_name] = model_params

    # Save all parameters to a single JSON file
    output_filename = 'all_crypto_logistic_regression_models_params.json'
    with open(output_filename, 'w') as f:
        json.dump(all_crypto_model_params, f, indent=4)

    print(f"\nAll model parameters saved to '{output_filename}'")
    print("\nExample of JSON content for one crypto:")
    if all_crypto_model_params:
        first_crypto_name = list(all_crypto_model_params.keys())[0]
        print(json.dumps({first_crypto_name: all_crypto_model_params[first_crypto_name]}, indent=4))
else:
    print("No trained models found or feature names not available for export.")

"""You can now download `logistic_regression_model_params.json` and use these coefficients and intercept in your JavaScript frontend to implement a simple logistic regression prediction function. For instance, in JavaScript, you would calculate `prediction = 1 / (1 + Math.exp(- (intercept + sum(feature * coefficient))))`."""

from google.colab import files

files.download('all_crypto_logistic_regression_models_params.json')

if model_evaluations:
    total_accuracy = 0
    num_models = 0
    for crypto_name, evaluation_results in model_evaluations.items():
        total_accuracy += evaluation_results['accuracy']
        num_models += 1

    if num_models > 0:
        average_accuracy = total_accuracy / num_models
        print(f"\nAverage Model Accuracy across all {num_models} cryptocurrencies: {average_accuracy:.4f}")
    else:
        print("No models were evaluated, so average accuracy cannot be calculated.")
else:
    print("No model evaluations available. Please ensure models were trained and evaluated successfully.")